### ISSUE TITLE
Create better `environ` variable names for base URLs

### ISSUE THREAD

**Issue by hhm970** [hhm970/c10-games-tracker-project#145]
## Description

We have very similar environment variable names for the website URL, which makes it a bit difficult to Terraform these values.

We should aim to have the name of the website we're extracting from into our environment variable names as a minimum.

Suggestion: we do it like so, `[WEBSITE_NAME]_BASE_URL`

## Required Files

N/A

## User Story

As engineers, we need to have informative and distinct variable names so that they can be used in all given situations without confusion.

**Comment by annalisev** [comment]
Done for GOG!
