### ISSUE TITLE
Execute Joni's comments

### ISSUE THREAD

**Issue by annalisev** [hhm970/c10-games-tracker-project#218]
## Description
Adapt the presentation slides to reflect Joni's comments

## Required Files
- https://docs.google.com/presentation/d/1_K3k_knlF4t6qXUvrfNAyUflgromNmmD_YYhG1otPsA/edit?usp=sharing

## User Story
As a watcher of the presentation I need good, clean, clear, and professional slides so I can clearly understand the information

**Comment by hhm970** [comment]
UPDATE: Joni gave us new feedback (01/05/2024):

- Problem slide; 2 graphs need to be more equally illustrated between them. Make sure to reverse how they're presented (historical graph first, then forecasting graph last).
- Product slide; arrows need to be of similar length and alignment. Design of bullet points needs to change (applies to other slides too).
- Stakeholders slide; needs to be more visually appealing
- Architecture diagram slide; consider magnifying on various elements of the diagram
- Reflection slide; make more visually appealing
