### ISSUE TITLE
Make the top 20 start from 1 and not 0

### ISSUE THREAD

**Issue by annalisev** [hhm970/c10-games-tracker-project#223]
## Description
I think this will just make a bit more sense on the dashboard

## Required Files
- Home.py

## User Story
As a user I need to see a clean and polished dashboard so I can trust the data.

**Comment by hhm970** [comment]
Done for dashboard on `Home.py` and all dashboards via `function.py`.

**Comment by hhm970** [comment]
Fixed a bug where this function would crash with less than 10 games
