### ISSUE TITLE
BUG: Architecture diagram not on main README.md

### ISSUE THREAD

**Issue by shindym** [hhm970/c10-games-tracker-project#298]
## Description
- Architecture diagram not on main README.md. Currently cannot find file

## Required Files
- `README.md`

**Comment by shindym** [comment]
Current:
`![Architecture Diagram](<diagrams/game-tracker.drawio.png>)`

- Spelling mistake -> should be `![Architecture Diagram](<diagrams/games-tracker.drawio.png>)`

**Comment by hhm970** [comment]
Sorry guys, I think this was my fault from not renaming the architecture diagram when I updated it on Wednesday/Thursday!
