### ISSUE TITLE
Missing docstrings

### ISSUE THREAD

**Issue by shindym** [hhm970/c10-games-tracker-project#300]
## Description
- write any missing docstrings

## User Story
As an engineer it is important to hand off work which has proper documentation and descriptions.

**Comment by shindym** [comment]
### Missing Docstrings
- Found after `pylint * .py`

************* Module extract.steam.test_extract_steam
extract/steam/test_extract_steam.py:3:0: E0401: Unable to import 'steam_extract' (import-error)
************* Module extract.steam.conftest
extract/steam/conftest.py:8:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:23:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:37:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:44:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:52:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:62:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:70:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/steam/conftest.py:92:0: C0116: Missing function or method docstring (missing-function-docstring)

************* Module extract.gog.conftest
extract/gog/conftest.py:1:0: C0114: Missing module docstring (missing-module-docstring)
extract/gog/conftest.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:24:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:31:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:38:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:45:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/gog/conftest.py:51:0: C0116: Missing function or method docstring (missing-function-docstring)

************* Module extract.epic.conftest
extract/epic/conftest.py:14:0: C0301: Line too long (103/100) (line-too-long)
extract/epic/conftest.py:1:0: C0114: Missing module docstring (missing-module-docstring)
extract/epic/conftest.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/epic/conftest.py:66:0: C0116: Missing function or method docstring (missing-function-docstring)
extract/epic/conftest.py:118:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by annalisev** [comment]
I didn't even think of conftest docstrings! I will do this now.
