### ISSUE TITLE
Correct architecture diagram on presentation

### ISSUE THREAD

**Issue by hhm970** [hhm970/c10-games-tracker-project#314]
## Description

On our presentation version of the architecture diagram, we have used incorrect terminology

- The diagram states that we extract data from the Steam website
- The diagram states that we scrape data from the EpicGames GraphQL API

## Required Files

https://app.diagrams.net/#G1X8IInVWSnxDjcfnKGqGfRyGfy5FWv8OB#%7B%22pageId%22%3A%22w82mywzxxPFvvJ6olz7Y%22%7D

## User Story

As an engineer, I need to ensure that my presentation diagrams and tools are accurately reflecting the project at hand, so that my client can get an accurate portrayal of the project

**Comment by shindym** [comment]
Diagrams updated to reflect corrected state.
