### ISSUE TITLE
Discuss presentation before meeting with Joni

### ISSUE THREAD

**Issue by hhm970** [hhm970/c10-games-tracker-project#35]
## Description

Brainstorm a rough structure of how we're going to present our project, as well as a 'big picture' of our project (eg. who is it for?)

## Required Files

[PHP_Storytelling and Presentations - C11.pdf](https://github.com/hhm970/c10-games-tracker-project/files/15075354/PHP_Storytelling.and.Presentations.-.C11.pdf)

## User Story

As engineers, we need to ensure that the product we create fulfils our clients' needs appropriately

**Comment by hhm970** [comment]
Spent half an hour discussing this; got a rough Google Doc and rough presentation explaining our thought process and how we intend to present

**Comment by shindym** [comment]
### Outcome of meeting
[google doc](https://docs.google.com/document/d/1v-4WkpsC1P0-dWyIfgelOuhp6ciyZU8v7hH8R1j1-80/edit?usp=sharing)

**Comment by shindym** [comment]
### To do
create a skeleton presentation in preparation for meeting with Joni
