### ISSUE TITLE
Readjust architecture diagram

### ISSUE THREAD

**Issue by hhm970** [hhm970/c10-games-tracker-project#50]
## Description

Refine and edit architecture diagram to reflect our project

## Required Files

https://app.diagrams.net/#G1eyiUtG28TyXLwHTw9276TIMAXI4Pgwh3#%7B%22pageId%22%3A%22w82mywzxxPFvvJ6olz7Y%22%7D

## User Story

As an engineer, I need to present the tools and programmes in the diagram clearly, so that my clients can understand how the product works and functions

**Comment by shindym** [comment]
### Discussion with Dan
- Lambda function for each source to extract from
- Step functions to run all of the extract -source lambdas  - triggered by Eventbridge daily
- Have release notifications as a separate lambda function run- triggered by Eventbridge daily
-  Remove old storage feature not required
- SNS for release notifications

**Comment by hhm970** [comment]
Architecture diagram has been successfully adjusted, gaining Dan's approval. Will need to simplify it for our presentation (which will be a different issue)

**Comment by shindym** [comment]
## updated Architecture Diagram

![Image](https://github.com/hhm970/c10-games-tracker-project/assets/73907929/f64b6cd5-dfb7-4195-8db2-c05269ecfbbb)
