### ISSUE TITLE
Create Architecture Diagram

### ISSUE THREAD

**Issue by annalisev** [hhm970/c10-games-tracker-project#6]
## Description
Create a first draft of an architecture diagram for our project.

## Required Files
- README.md

## User Story
As engineers we need to have a detailed understanding of our pipeline so we can stay on track with our tasks.

**Comment by hhm970** [comment]
- Created 1st draft for architecture diagram, outlining the basic pipeline, dashboarding process, and cloud storage solutions.
- Still deciding on the best approach to problem, and the associated tools used to fulfil our approach

**Comment by shindym** [comment]
Building on  #14 
- Make architecture diagram in draw.io.

**Comment by shindym** [comment]
[Architecture Diagram](https://drive.google.com/file/d/1eyiUtG28TyXLwHTw9276TIMAXI4Pgwh3/view?usp=sharing)

- Storage method might require reworking based on data requirements.
