### ISSUE TITLE
Create initial presentation from skeleton & Jonis feedback

### ISSUE THREAD

**Issue by shindym** [hhm970/c10-games-tracker-project#75]
## Description
- Create an initial presentation from skeleton & joni's feedback 

### Joni's feedback
- Practice connecting to technology in TIG room
- First introduce ourselves and our roles with the project before into problem slide
Problem slide: story tell from the user perspective 
-Solution slide
Dashboard:
- Pushing data out to customers
-Architecture diagram: going to refine with dan
-Q for Dan: How long to talk about this, level of detail to go in to
-Do demo first? To spark audience interest, non-technical audience will then have more context when the architecture diagram is explained
Demo: 
be really clear when showing Steam etc that this is NOT our work
Next steps + reflection: really nice and nice to reflect
Add theme + colours
Add more storytelling
Present professionally, be confident, bring the fun out- gaming is fun - logos, small jokes
Dress smartly

## Required Files
- google slides
- [project skeleton](https://docs.google.com/presentation/d/1Ptqqyf0k5kfe6dZ9R5yisipeuNrhPKrFOcqFEWEalhg/edit?usp=sharing)

## User Story
- As an engineer it is an important part of the project to be able to effectively present the project to a wider audience both technical and non technical

**Comment by annalisev** [comment]
Scheduled for Friday afternoon.

**Comment by annalisev** [comment]
https://docs.google.com/presentation/d/1_K3k_knlF4t6qXUvrfNAyUflgromNmmD_YYhG1otPsA/edit#slide=id.g2d009de875a_0_209
